CC=gcc -std=c99 -Wall -pedantic
math=-lm

all:
	$(CC) $(math) as05-scolaro-s4320824.c -o as05-scolaro-s4320824

debug:
	$(CC) $(math) -g as05-scolaro-s4320824.c -o as05-scolaro-s4320824

clean:
	rm *.o
