CC=gcc -std=c99 -Wall -pedantic
math=-lm

all:
	$(CC) $(math) as02-scolaro-s4320824.c -o as02-scolaro-s4320824

debug:
	$(CC) $(math) -g as02-scolaro-s4320824.c -o as02-scolaro-s4320824

clean:
	rm *.o
