CC=gcc -std=c99 -Wall -pedantic
math=-lm

all:
	$(CC) $(math) as11-scolaro-s4320824.c -o as11-scolaro-s4320824

debug:
	$(CC) $(math) -g as11-scolaro-s4320824.c -o as11-scolaro-s4320824

clean:
	rm *.o
