CC=gcc -std=c99 -Wall -pedantic
math=-lm

all:
	$(CC) $(math) as09-scolaro-s4320824.c -o as09-scolaro-s4320824

debug:
	$(CC) $(math) -g as09-scolaro-s4320824.c -o as09-scolaro-s4320824

clean:
	rm *.o
