CC=gcc -std=c99 -Wall -pedantic
math=-lm

all:
	$(CC) $(math) as07-scolaro-s4320824.c -o as07-scolaro-s4320824

debug:
	$(CC) $(math) -g as07-scolaro-s4320824.c -o as07-scolaro-s4320824

clean:
	rm *.o
